[package]
name = "snake"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.12.1", features = ["dynamic_linking"] }
image = "0.24.8"
rand = "0.8.5"
winit = "0.28.7"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
